services:
  bind9:
    image: ubuntu/bind9
    container_name: asir_bind9
    ports:
      - 53:53/tcp
      - 53:53/udp
    
    networks:
      bind9_subnet:
        ipv4_address: 172.28.5.1
    
    volumes:
      - ./conf:/etc/bind
      - ./zonas:/var/lib/bind
    environment:
      - TZ=Europe/Paris


  asir_cliente:
    image: alpine
    container_name: asir_cliente
    ports:
      - 80:80/tcp
      - 80:80/udp
    networks:
      bind9_subnet:
        ipv4_address: 172.28.5.2
    
    volumes:
      - ./conf:/etc/bind
      - ./zonas:/var/lib/bind

networks:
  bind9_subnet: 
    external: true
