services:
 asir_cliente:
    container_name: asir_cliente_alpine
    image: alpine
    tty: true         # docker run -t
    stdin_open: true
    #para que el cliente use nuestro DNS
    dns:
      - 172.28.5.1  # el contenedor dns
    networks:
      bind9_subnet: 
       ipv4_address: 172.28.5.2  
networks:
    bind9_subnet:
     external: true  
  