# Contenedor de apache
services:

  asir_sitio1:
    container_name: asir_sitio1
    image: httpd:2.4
    ports:
      - "8000:80"
    # mapeamos el directorio raiz
    volumes:
      - ./paginas:/usr/local/apache2/htdocs
      - ./confApache:/usr/local/apache2/conf
    networks:
     my-network:
        # ip fija del contenedor
       ipv4_address: 172.30.0.30

  # contenedor servidor de dns - bind9
  asir_sitio2:
    container_name: asir_sitio2
    # usamos esta imagen para poder ver los logs
    # la imagen de internetsystemsconsortium/bind9
    # no muestra los logs
    image: ubuntu/bind9
    # especificamos la plataforma de la imagen
    # es posible conflicto si el host es 'arm' porque no existe una imagen para esa plataforma
    platform: linux/amd64
    ports:
      - "53:53"
      
    volumes:
      - ./paginas:/usr/local/apache2/htdocs
      - ./conf:/etc/bind
      - ./zonas:/var/lib/bind

    networks:
     my-network:
        # ip fija del contenedor
       ipv4_address: 172.30.0.40
    
  dns-server:
    container_name: asir_dns_tarea7
    image: pihole/pihole:latest
    networks:
      my-network:
        ipv4_address: 172.30.0.50


# red propia
networks:
  my-network:
    ipam:
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1
