services:

  asir_ejercicio1:
    container_name: asir_ejercicio1
    image: httpd:2.4
    ports:
      - "8000:80"
      - "80:80"
    volumes:
      - ./paginas:/usr/local/apache2/htdocs
      - ./confApache:/usr/local/apache2/conf
    networks:
     my-network:
       ipv4_address: 172.17.0.30
    #dns:
    #- 

  asir_ejercicio2:
    container_name: asir_ejercicio2
    image: ubuntu/bind9
    platform: linux/amd64
    ports:
      - "53:53"
    volumes:
      - ./paginas:/usr/local/apache2/htdocs
      - ./conf:etc/bind
      - ./zonas:var/lib/bind
    networks:
     my-network:
       ipv4_address: 172.17.0.40

networks:
  my-network:
    ipam:
      config:
        - subnet: 172.17.0.0/16
          gateway: 172.17.0.1
          